on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy App
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Generate GITHUB_SHA
      id: github-sha
      shell: bash
      run: |
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        echo "::set-output name=sha::$SHORT_SHA"
    - name: Publish Image to Digital Ocean Container Registry
      shell: bash
      run: |
        doctl registry login --expiry-seconds 600
        docker build . -t registry.digitalocean.com/sample-go/add_sample:${{steps.github-sha.outputs.sha}}
        docker push registry.digitalocean.com/sample-go/add_sample:${{steps.github-sha.outputs.sha}}
    - name: DigitalOcean App Platform deployment
      uses: ParamPatel207/app_action@main
      with:
        app_name: sample-golang
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        images: '[
                          {
                            "name": "web",
                            "repository": "registry.digitalocean.com/sample-go/add_sample",
                            "tag": "${{steps.github-sha.outputs.sha}}"
                          }
                        ]'
